version: 1.0.{build}
image:
- Visual Studio 2017
clone_depth: 1

artifacts:
- path: jupyterq_windows-$(appveyor_repo_tag_name).zip
skip_non_tags: false
platform: x64

build_script:
- cmd: >-

    build\buildscript.bat

    tests\test.bat

after_build:
- cmd: >-

    if "%APPVEYOR_REPO_TAG%"=="true" ( 7z a jupyterq_windows-%APPVEYOR_REPO_TAG_NAME%.zip jupyterq_*.q w64/jupyterq.dll install.bat kxpy kernelspec examples kdb+Notebooks.ipynb LICENSE README.md && appveyor PushArtifact jupyterq_windows-%APPVEYOR_REPO_TAG_NAME%.zip )

    if "%APPVEYOR_REPO_TAG%"=="false" ( 7z a jupyterq_windows-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.zip jupyterq_*.q w64/jupyterq.dll install.bat kxpy kernelspec LICENSE README.md examples kdb+Notebooks.ipynb && appveyor PushArtifact jupyterq_windows-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%.zip )
deploy:
 release: $(appveyor_repo_tag_name)
 provider: GitHub
 auth_token: $(GITHUB_APIKEY)
 on:
  appveyor_repo_tag: true
 

